default: &default
  adapter:  postgresql
  encoding: utf8
  host:     <%= ENV.fetch "DB_HOST" %>
  port:     <%= ENV.fetch "DB_PORT" %>
  password: <%= ENV.fetch "DB_PASSWORD" %>
  username: <%= ENV.fetch "DB_USERNAME" %>
  pool:     <%= ENV.fetch "DB_POOL", 5 %>

development:
  <<: *default
  database: <%= ENV.fetch "DB_NAME" %>_development

development:
  <<: *default
  database: <%= ENV.fetch "DB_NAME" %>

test:
  <<: *default
  database: <%= ENV.fetch "DB_NAME" %>_test
